---
abstract: "Prevent empty reciepent lists when replying to tickets."
author:
  - 'The Networking People (NorthWest) Limited.'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-NoEmptyCorrespond
no_index:
  directory:
    - html
    - inc
requires:
  perl: 5.8.3
resources:
  license: https://opensource.org/licenses/MIT
  repository: https://github.com/TNP-Ltd/rt-extension-noemptycorrespond
version: '1.02'
x_module_install_rtx_version: '0.38'
x_requires_rt: 4.0.3
x_rt_too_new: 4.6.0
